### ISSUE TITLE
Some questions in the reproduction process

### ISSUE THREAD

**Issue by MAX-OTW** [amaralibey/gsv-cities#10]
Hello, @amaralibey ,first of all,many thanks for your work!I really appreciate for your great work :) When I reproduced, I had some problems and needed help.

1、How to test the pitts250k val/test dataset with the trained weights?
2、If something unexpected happens that stops the training, how to continue training on the basis of the existing trained weight?
3、If I want to obtain a list of the top N images retrieved for each query in the test dataset in the test stage.It just need to output a txt file( including the prediction results ).How to to achieve this？
4、I noticed that PCA algorithm was used in the paper, but I didn't find it in the code. May I ask how to implement it？

I am always looking forward to your kind response:)
Best regards.

**Comment by amaralibey** [comment]
Hello @MAX-OTW,
Thank you for your interest in our work,

1- I just added the code and procedure to test on pitts30k-val, pitts30k-test and pitts250k-test ([Notebook](https://github.com/amaralibey/gsv-cities/blob/main/notebooks/evaluate_model.ipynb))

2- PyTorch lightning supports "resume training" from checkpoint, you can look up their website for more details. You can add the argument `resume_from_checkpoint` to the Trainer object in `main.py` and give it the path as follows:
```
trainer = pl.Trainer(resume_from_checkpoint='./LOGS/resnet50/...../your_saved_checkpoint.ckpt',
                                   accelerator='gpu', devices=[0],
                                   default_root_dir=f'./LOGS/{model.encoder_arch},
                                   ...)
```

3- If you look closely, when we call `get_validation_recalls`, it returns recalls in a dict and ALSO an array `preds`. The preds are the indices of the top N matching references (by order of L2 similarity) for each query (each line of the array).

4- For PCA, I simply used FAISS for that ([LINK](https://github.com/facebookresearch/faiss/wiki/Faiss-building-blocks:-clustering,-PCA,-quantization)). I also tried PCA implementation of OpenIBL ([LINK](https://github.com/yxgeee/OpenIBL/blob/master/ibl/pca.py)). They both give similar results, but I prefer FAISS for integration.

Best regards.

**Comment by MAX-OTW** [comment]
Thank you very much for your advice:)
Best regards.

**Comment by Lisachinasd** [comment]
Hello, about default_root_dir error: how to modify the default path default_root_dir? Run the main. No response to py, tip Missing logger folder: LOGS/resnet50 / lightning_logs
