### ISSUE TITLE
traindataset

### ISSUE THREAD

**Issue by libenchong** [amaralibey/gsv-cities#11]
Hello @amaralibey.
When constructing the training set, the order of places within a city is shuffled, whereas there is an order between cities because buildings within a city share a similar architectural style, whereas architectural styles differ between cities.

**Comment by amaralibey** [comment]
Hello @libenchong,
That's right, in training, we only shuffle in-city to maximise the percentage of informative pairs/triplets. You have the option in the code to shuffle all place. The training might take longer to achieve the same performance. If you are interested in squeezing the maximum information with informative batch sampling, take a look at our BMVC paper: https://bmvc2022.mpi-inf.mpg.de/958/
