### ISSUE TITLE
Dataset image "panoid" generation rules

### ISSUE THREAD

**Issue by whu-lyh** [amaralibey/gsv-cities#16]
May I ask how you generate the image "panoid" ? such as "7P0FnGV3k4Fmtw66b8_-Gg"

**Comment by amaralibey** [comment]
Hello @whu-lyh,
The panoid serves as a distinctive identifier assigned to individual Google Street View panoramas. These identifiers are provided by Google, and the specific method used to generate them remains undisclosed.
