### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by aleshem** [amaralibey/gsv-cities#19]
Hi I did not find a license file in your repo. Can you add one please? is it MIT license?
Fantastic work!

**Comment by amaralibey** [comment]
Hello @aleshem, thank you for your interest.
The source code in this repository is under the MIT license (I will add the LICENSE file soon).

The GSV-Cities dataset is hosted on Kaggle at [this link](https://www.kaggle.com/datasets/amaralibey/gsv-cities) and is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 4.0 International (CC BY-NC-ND 4.0) License, which you can view [here](https://creativecommons.org/licenses/by-nc-nd/4.0/).
