### ISSUE TITLE
Full release of code and dataset

### ISSUE THREAD

**Issue by Vincentqyw** [amaralibey/gsv-cities#2]
Hi amar,

Thank you for the amazing repo. 

I am working on a similar project involving VPR ,  your data introduced in paper fit me well.

I just wondering when will the full release the code and dataset.

Thx again.

**Comment by amaralibey** [comment]
Hello and thank you for your interest :)

We are sorry for the delay, we have opened access to the dataset. Please refer to README for download instructions.

Best regards,
