### ISSUE TITLE
Dataset availability 

### ISSUE THREAD

**Issue by learn2phoenix** [amaralibey/gsv-cities#3]
The [paper](https://arxiv.org/pdf/2210.10239.pdf) says that the dataset and code are available. But I don't see the dataset link anywhere on this repo. Am I missing something?

**Comment by amaralibey** [comment]
Hello,

We are sorry for the delay, we just opened access to the dataset. Please refer to README for download instructions.
other parts of the code (framework, loss functions and Conv-AP technique will soon follow).

Best regards,
