### ISSUE TITLE
SPED and Nordland dataset

### ISSUE THREAD

**Issue by libenchong** [amaralibey/gsv-cities#8]
Hi,@amaralibey
SPED and Nordland dataset codes are  not available. Can you release two dataset code?

**Comment by amaralibey** [comment]
Hi @libenchong,
I did not write code for those two datasets, I simply used VPR-Bench (https://github.com/MubarizZaffar/VPR-Bench). 
I added the models that I trained and run the benchmark with their code.

**Comment by libenchong** [comment]
Ok, thank you for the link

**Comment by MAX-OTW** [comment]
Hello, @amaralibey ,first of all, thank you so much for your work! It's great!
However, I have a question that needs your help. May I ask how to use your model to evaluate SPED and Nordland dataset?At present, I have encountered some difficulties. Could you please provide relevant codes?

I would appreciate it if you could help me, and hope to receive your reply as soon as possible!

**Comment by amaralibey** [comment]
Hi @MAX-OTW,

I have updated the code, you can now evaluate on SPED, Norland and many other. Just follow the instructions in https://github.com/amaralibey/gsv-cities/blob/main/notebooks/evaluate_model.ipynb

Thank you for your interest,
