### ISSUE TITLE
release pre-trained model

### ISSUE THREAD

**Issue by WalkerWen** [amaralibey/gsv-cities#9]
Hi amar,

Thank you for the amazing repo.

I'm interested in VPR, however, restricted by machine(GPU), it's a little hard for me to train all the data. So I want to know if you will release the pre-training model.

Thanks

**Comment by amaralibey** [comment]
Hi @WalkerWen,

We have released the pretrained weights today, you can read about them in the front page of this repo.
Thank you for your interest.
